### ISSUE TITLE
Add music to the game

### ISSUE THREAD

**Issue by Y-LyN-10** [CymbidiumOrchid/NakMan#5]
Anyone? Ideas, action? Who wants to do this? :)

**Comment by RoYaLBG** [comment]
As a materials issue, I'm assigning this one to @petrovaliev95 
The main goal here is some awful long audio on the background.
So, @Daniel, please find long version of Nyan cat and extract the audio only.

As an optional addition:
Cut from Nakov speeches things like "Pederas" and mix them with Nyan cat's audio.
