### ISSUE TITLE
Level schema

### ISSUE THREAD

**Issue by RoYaLBG** [CymbidiumOrchid/NakMan#6]
Draw a new level schema, as the current one is very simple.
Have in mind that ghosts (Nakov's entourage) needs to reach a collision before make a turn, so write as much as possible collisions with 2 choices (as the ghost collides, it decides to turn whether right or left(up/or down) depending where the player is).

**Comment by RoYaLBG** [comment]
Tip: Put your ticket URLs into your commit message

**Comment by Y-LyN-10** [comment]
9eef764cda9f02c562f86f98180ed763543583aa Is that map okay?

**Comment by RoYaLBG** [comment]
Great
