### ISSUE TITLE
Delete IDE Metadata directories

### ISSUE THREAD

**Issue by RoYaLBG** [CymbidiumOrchid/NakMan#7]
Find and removeany metadata directories created by IDE's either added by you or by someone else in the repository.
In addition, put metadata directories out of the working copy directory or set them in the .gitignore configuration (or, svn, if you are using one). 

A repository should only hold files related to the project build.

**Comment by RoYaLBG** [comment]
Tip: Put your ticket URLs into your commit message

**Comment by danielpetrovaliev** [comment]
I deleted metadata directories.

**Comment by RoYaLBG** [comment]
Approved. Commit revision: https://github.com/CymbidiumOrchid/NakMan/commit/e63c1aa647209fa11c13b579f94434021d2d3430

**Comment by Y-LyN-10** [comment]
ed2672ece0ad297d34f3cea26da051fe35c545e3 All clear for now.
